# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('price_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CartFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('fineness_from', models.IntegerField(null=True)),
                ('fineness_to', models.IntegerField(null=True)),
                ('price_from', models.IntegerField(null=True)),
                ('price_to', models.IntegerField(null=True)),
                ('weight_from', models.IntegerField(null=True)),
                ('weight_to', models.IntegerField(null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartMetalFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Jewel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('fineness', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to=b'Images/')),
                ('description', models.CharField(default=b'', max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('price_total', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Jewel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Order')),
            ],
        ),
        migrations.AddField(
            model_name='jewel',
            name='metal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Metal'),
        ),
        migrations.AddField(
            model_name='cartmetalfilter',
            name='metal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Metal'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.Jewel'),
        ),
    ]
