# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_auto_20160928_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.UUIDField(default=None),
        ),
    ]
