# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_auto_20160929_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
