# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_auto_20160929_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session',
            field=models.CharField(max_length=32),
        ),
    ]
