# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_auto_20160929_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session',
        ),
    ]
