# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0021_remove_order_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
