# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0022_remove_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
